### PR TITLE
Final editorial changes: Open Document Format for Office Applications (OpenDocument) Version 1.3 Committee Specification

### PR DESCRIPTION
**Pull request by svanteschubert**
Pull-request for the tasklist taken from the [official TC ADMIN JIRA issue](https://issues.oasis-open.org/browse/TCADMIN-3832?focusedCommentId=78296&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-78296) issue by Paul Knight from OASIS.

### CODE REVIEW

**Comment by mistmist** [comment]
LGTM so far

**Comment by svanteschubert** [comment]
Style colour change due to OASIS logo update (search/replace in styles.xml)

1. Titles & Headings
    * #446caa -> #2248e5
1. Hyperlinks
    * #0000ee -> #55308d
    * #800080 -> #55308d
    * #0000ff  -> #55308d
1.  Style "Placeholder" in part3 & part4
    * #008080	-> 80e9ff

**Comment by svanteschubert** [comment]
@mistmist 
All yours, Michael. Could you assign it afterwards to Paul Knight, please? (GitHubID:  paul-knight)

Thanks!

**Review by mistmist — COMMENTED** [review]
LGTM

**Pull request merged**
